server:
  port: 2002

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
       defaultZone: http://localhost:2002/eureka/,http://localhost:2001/eureka/,http://localhost:2003/eureka/