server:
  port: 7005

eureka:
  client:
    serviceUrl:
           defaultZone: http://localhost:2001/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: zuul

zuul:
  routes:
    api-demo:
      path: /api-demo/**
      serviceId: service-demo
  retryable: true

ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 1500
  ConnectTimeout: 1500

hystrix:
    command:
        default:
            execution:
              timeout:
                  enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 3500



##是否开启重试功能
#zuul.retryable=true
##对当前服务的重试次数
#ribbon.MaxAutoRetries=2
##切换相同Server的次数
#ribbon.MaxAutoRetriesNextServer=0
