eureka:
  client:
    serviceUrl:
           defaultZone: http://localhost:2001/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: zuul

zuul:
  routes:
    api-demo:
      path: /api-stream/**
      serviceId: service-stream
    api-movie:
      path: /api-movie/**
      serviceId: service-movie
  retryable: true #开启重试

ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 3500
  ConnectTimeout: 3500

hystrix:
    command:
        default:
            execution:
              timeout:
                  enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 3500
    threadpool:
      default:
        coreSize: 200 #并发执行的最大线程数，默认10
              maxQueueSize: 1000 #BlockingQueue的最大队列数，默认值-1
              queueSizeRejectionThreshold: 800 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5


##是否开启重试功能
#zuul.retryable=true
##对当前服务的重试次数
#ribbon.MaxAutoRetries=2
##切换相同Server的次数
#ribbon.MaxAutoRetriesNextServer=0
